CREATE TABLE USERS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMRI VARCHAR(50) NOT NULL,
    MBIEMRI VARCHAR(50) NOT NULL,
    E_KOMPANIS VARCHAR(50) NOT NULL,
    TELEFON VARCHAR(50) NOT NULL,
    ADRESA VARCHAR(255) NOT NULL,
    LLOJI_KLIENTIT VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    ISACTIVE BOOLEAN NOT NULL DEFAULT true
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);

CREATE TABLE ROLES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_ID INT NOT NULL,
    ROLE_NAME VARCHAR(50) NOT NULL,
    ROLE_ISACTIVE BOOLEAN NOT NULL DEFAULT true
    ROLE_ISADMIN BOOLEAN NOT NULL DEFAULT false
);

INSERT INTO ROLES (ROLE) VALUES ('Admin'), ('User');
CREATE TABLE UserTokens(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    EXPIRATION_DATE DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
CREATE TABLE PROJECTS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMERTIMI VARCHAR(50) NOT NULL,
    PERSHKRIMI VARCHAR(255) NULL,
    KLIENTI_ID INT NOT NULL,
    LOKACIONI VARCHAR(255)  NULL,
    BUXHEITI DECIMAL(18,2)  NULL,
    DATA_FILLIMIT DATE NOT NULL,
    DATA_PERFUNDIMIT DATE NULL,
    STATUSI VARCHAR(50)  NULL,
    PROGRESI_TOTAL INT NOT NULL DEFAULT 0,
    FOREIGN KEY (KLIENTI_ID) REFERENCES USERS(ID)
    );

